### ISSUE TITLE
  Extra parenthesis in `tpl/starterbootstrap/lang/fr`

### ISSUE THREAD

**Issue by eliemichel** [wwu-housing/starterbootstrap#69]
```
PHP Parse error:  syntax error, unexpected ')' in /d1/www/dokuwiki/lib/tpl/starter-bootstrap/lang/fr/lang.php on line 16
```

Using last stable version.

I solved it simply by removing the parenthesis, but I do not know where that `starter-bootstrap` directory comes from (as I did not look further at dokuwiki code) so I cannot do a PR.

**Comment by apexskier** [comment]
The starter-bootstrap directory is where your instance of this template is installed. You may have installed it before the name was changed from "starter-bootstrap" to "starterbootstrap".

It looks like you don't have the latest version, see https://github.com/wwu-housing/starterbootstrap/blob/master/lang/fr/lang.php#L16. This issue was resolved in #13.
